/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
#ifndef __NET_PBB_H_
#define __NET_PBB_H_

enum {
	IFLA_PBB_I_UNSPEC,
	IFLA_PBB_I_CORE_BRIDGE_INFO,
	IFLA_PBB_I_CVID_INFO_RANGE_BEGIN,
	IFLA_PBB_I_CVID_INFO_RANGE_END,
	IFLA_PBB_I_CVID_INFO_ACTION,
	IFLA_PBB_I_SVID_INFO_RANGE_BEGIN,
	IFLA_PBB_I_SVID_INFO_RANGE_END,
	IFLA_PBB_I_SVID_INFO_ACTION,
	IFLA_PBB_I_ISID_INFO_RANGE_BEGIN,
	IFLA_PBB_I_ISID_INFO_RANGE_END,
	IFLA_PBB_I_ISID_TYPE,
	IFLA_PBB_I_KEY_INFO_MAP_VERIFY,
	IFLA_PBB_I_MAX,
};

enum pbb_i_sid_mode {
	PBB_I_ISID_TYPE_SHARED,
	PBB_I_ISID_TYPE_EXCL,
	PBB_I_ISID_TYPE_MAX,
};

enum pbb_i_vid_info_action {
	PBB_I_VID_INFO_ACTION_KEEP,
	PBB_I_VID_INFO_ACTION_STRIP,
	PBB_I_VID_INFO_ACTION_MAX,
};

enum {
	IFLA_PBB_B_UNSPEC,
	IFLA_PBB_B_LINK,
	IFLA_PBB_B_B_VID_MODE,
	IFLA_PBB_B_ISID_INFO_RANGE_BEGIN,
	IFLA_PBB_B_ISID_INFO_RANGE_END,
	IFLA_PBB_B_VID_INFO_RANGE_BEGIN,
	IFLA_PBB_B_VID_INFO_RANGE_END,
	IFLA_PBB_B_KEY_INFO_MAP_VERIFY,
	IFLA_PBB_B_MAX,
};

enum pbb_b_mode {
	PBB_B_MODE_DOT1Q,
	PBB_B_MODE_DOT1AD,
	PBB_B_MODE_MAX,
};

#endif //__NET_PBB_H_
